# Generated by Django 3.0.8 on 2020-08-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Anonymous User', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='session_token',
            field=models.CharField(default='0', max_length=250),
        ),
    ]
